---
- name: restart sshd
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: reload nftables
  ansible.builtin.systemd:
    name: nftables
    state: reloaded

- name: restart fwknop
  ansible.builtin.systemd:
    name: fwknop-server
    state: restarted

- name: restart caddy
  community.docker.docker_container:
    name: caddy
    restart: true

- name: restart xray
  community.docker.docker_container:
    name: xray
    restart: true

- name: restart adguardhome
  community.docker.docker_container:
    name: adguardhome
    restart: true

- name: restart mtg
  community.docker.docker_container:
    name: mtg
    restart: true

- name: restart mtg pool
  ansible.builtin.systemd:
    name: "mtg@{{ item.port }}.service"
    state: restarted
    daemon_reload: true
  loop: "{{ mtg_per_user_pool_items | default([]) }}"
  loop_control:
    label: "port={{ item.port }}"

- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
